# Generated by Django 4.0.2 on 2022-04-06 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TestUser',
            fields=[
                ('userid', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ResourceDatabase',
            fields=[
                ('resourceID', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('sname', models.CharField(max_length=30)),
                ('topic', models.TextField()),
                ('resourceDesc', models.TextField(blank=True, null=True)),
                ('file', models.FileField(upload_to='resource/resourcePdf')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interview.testuser')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=15)),
                ('branch', models.CharField(max_length=30)),
                ('company_name', models.CharField(max_length=30, null=True)),
                ('yoj', models.IntegerField(null=True)),
                ('linkedIn', models.URLField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewDatabase',
            fields=[
                ('interviewID', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('year', models.IntegerField()),
                ('cname', models.CharField(max_length=30)),
                ('branch', models.CharField(max_length=30)),
                ('title', models.TextField()),
                ('interexp', models.TextField()),
                ('file', models.FileField(blank=True, null=True, upload_to='interview/interviewPdf')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Interview.testuser')),
            ],
        ),
    ]
