# Generated by Django 3.2.12 on 2022-05-03 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Interview', '0002_remove_interviewdatabase_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='forget_pwd_token',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
